FROM sconecuratedimages/iexecsgx:cli

### install dependencies you need
RUN apk add bash nodejs-npm
RUN SCONE_MODE=sim npm install node-fetch@2.6.x
RUN SCONE_MODE=sim npm install ethers@5.1.0
RUN SCONE_MODE=sim npm install jsonpath@1.1.x
RUN SCONE_MODE=sim npm install big.js@6.0.x
RUN SCONE_MODE=sim npm install yup@0.32.x



COPY ./src /app

###  protect file system with Scone
COPY ./protect-fs.sh ./Dockerfile /build/
RUN sh /build/protect-fs.sh /app

ENTRYPOINT [ "node", "/app/app.js"]